// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BooksAPI.Models;

public partial class Author
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Biography { get; set; }

    public virtual ICollection<Book> Books { get; set; } = new List<Book>();
}