// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BooksAPI.Models;

public partial class Book
{
    public int Id { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public int AuthorId { get; set; }

    public int GenreId { get; set; }

    public int PublishedYear { get; set; }

    public string Isbn { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Author Author { get; set; }

    public virtual Genre Genre { get; set; }
}